# Generated by Django 3.2.21 on 2023-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_post_cb3u4j', upload_to='images/'),
        ),
    ]
